version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.6
      python: 3.7
    commands:
      - sudo gem install cfn-nag
  pre_build:
    commands:
      - printenv
      - ls -lha
  post_build:
    commands:
      - cfn_nag_scan --input-path serverless-website.yml