version: 0.2

phases:
  runtime-versions:
    ruby: 2.6
    python: 3.7
  pre_build:
    commands:
      - ls -lha
      - cat buildspec.yml
      - printenv
      - STACKNAME=serverless-website
      - sudo apt-get update
      - sudo apt-get install jq
  build:
    commands:
      - echo Build and package code
      - >
        aws cloudformation deploy --template-file serverless-website.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --stack-name $STACKNAME \
            --region us-west-2 \
            --no-fail-on-empty-changeset \
            --parameter-overrides file://parameters.json
            # --tags file://tags.json || 
            # $(printf "aws cloudformation describe-stack-events \
            #         --stack-name %s \
            #         --output table \
            #         --query 'StackEvents[?Timestamp >= \`%s\`].[Timestamp,ResourceType,LogicalResourceId,ResourceStatus,ResourceStatusReason]'" $STACKNAME $TIME | sh && exit 1)
  post_build:
    commands:
      - aws cloudformation describe-stacks --stack-name ${STACKNAME} --query 'Stacks[*].Outputs' | jq '.[]' > ./cloudformation-outputs.json

