version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.6
      python: 3.7
  pre_build:
    commands:
      - ls -lha
      - cat buildspec-qa.yml
      - printenv
      - STACKNAME=serverless-website
      - sudo apt-get update
      - sudo apt-get install jq
      - cat cloudformation-outputs.json
      - pip install requests
      - pip install --upgrade pyopenssl
  build:
    commands:
      - API_ENDPOINT=$(cat cloudformation-outputs.json | jq .[].OutputValue)
      - python -c "import requests;requests.packages.urllib3.disable_warnings();response = requests.get(url=${API_ENDPOINT}, verify=False);print(response)"
      - if [ $? -ne 0 ] ; then echo "Unable to resolve endpoint. Test failed";exit 1 ; fi